### PR TITLE
Minor changes in look and feel of page

### PR DESCRIPTION
**Pull request by ajiteshr7**
Added spacing between registration cards

### CODE REVIEW

**Comment by faheel** [comment]
It would be better to add the left and right margin in the `registration-column` class in `custom.css` than in the HTML.

**Comment by ajiteshr7** [comment]
changing registration-column class may cause confusion if it is used in future,
though adding a custom class will do the job.

**Comment by faheel** [comment]
Yeah, a custom class would be better.

**Comment by faheel** [comment]
Duplicate of #12

**Pull request closed without merging**
